apiVersion: core.kyma-project.io/v1beta1
kind: RegistryCacheConfig
metadata:
  labels:
    app.kubernetes.io/name: kim-snatch-webhook
    app.kubernetes.io/managed-by: kustomize
  name: registrycacheconfig-sample
spec:
  # TODO(user): Add fields here
